{
 "title": "Spark: Jobs Details",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Dispatcher 0 Offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_framework_offers{framework_name=\"spark-tests-2018-06-05__spark-00\"}"
    }
   ]
  },
  {
   "title": "# Currently launched by dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_drivers_launched" }
   ]
  },
  {
   "title": "# Dispatchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_drivers_launched)"
    }
   ]
  },
  {
   "title": "Job duration (min.) mean",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_drivers_launch_to_finish_state_finished_mean_mean / 60000"
    }
   ]
  },
  {
   "title": "offers_received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "offers_received" }
   ]
  },
  {
   "title": "Median Submit to First Launch (stacked)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_driver_submit_to_first_launch_p50",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Job launch time (sec) - driver start to all executors launched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_cluster_executor_start_to_all_launched_mean / 1000"
    }
   ]
  },
  {
   "title": "Number of Job Failures by Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_cluster_driver_finished_count_mesos_state_task_failed) by (task_name)"
    }
   ]
  },
  {
   "title": "Driver Launches by Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_drivers_launched", "legendFormat": "{{task_name}}" }
   ]
  },
  {
   "title": "Job Launch Time (sec.) by Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_executor_start_to_all_launched_mean / 1000) by (dcos_space)"
    }
   ]
  },
  {
   "title": "# Currently launched / waiting / retry jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_drivers_launched)",
     "legendFormat": "launched"
    },
    {
     "expr": "sum(spark_mesos_drivers_waiting)",
     "legendFormat": "waiting"
    },
    { "expr": "sum(spark_mesos_drivers_retry)", "legendFormat": "retry" }
   ]
  },
  {
   "title": "Queue Depth by Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_drivers_waiting" }
   ]
  },
  {
   "title": "Executor count by job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_mesos_executor_count" }
   ]
  },
  {
   "title": "Median Submit to First Launch",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_mesos_drivers_submit_to_first_launch_p50_mean",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}